/**
* @author Gil Avignon
* @date 09/05/2018
* @description  Constant Utility Class
* @group Utility
*/
public class UTIL_Constants {
    public static String AUTHENTICATION_TYPE_ACCESS_TOKEN = 'Access Token';
    public static String AUTHENTICATION_TYPE_API_KEY = 'API Key';
    public static String AUTHENTICATION_TYPE_BASIC = 'Basic';

    public static String LOG_TYPE_ERROR = 'Error';
    public static String LOG_TYPE_DEBUG = 'Debug';

    public static String REQUEST_HEADER_KEY = 'Authorization';
    public static String REQUEST_HEADER_KEYID = 'KeyId';
    public static String REQUEST_HEADER_TRACE_ORG = 'X-SFDC-OrgId';
    public static String REQUEST_HEADER_TRACE_USER = 'X-SFDC-UserId';
    public static String REQUEST_HEADER_TRACE_ENTITY = 'X-SFDC-EntityId';

    public static String ORG_NAME_DEV = 'Dev';
    public static String ORG_NAME_PRD = 'PRD';
    public static String ORG_NAME_DEFAULT = 'Default';
}
